### ISSUE TITLE
calling evm contract could not 'eosapi' from tests.evm.evm.et script

### ISSUE THREAD

**Issue by gnufoo** [learnforpractice/pyeos#68]
from tests.evm.evm import et
<stdin>:Greeter
[{'constant': False, 'inputs': [], 'name': 'getValue', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': True, 'stateMutability': 'payable', 'type': 'function'}, {'constant': False, 'inputs': [{'name': 'v', 'type': 'uint256'}], 'name': 'setValue', 'outputs': [], 'payable': True, 'stateMutability': 'payable', 'type': 'function'}, {'inputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'}]
----request_func eth_estimateGas [{'from': '0x88224Fe4e4954C29d1D765eBe39331186fC259CF', 'to': '0x88224Fe4e4954C29d1D765eBe39331186fC259CF', 'data': '0x55241077000000000000000000000000000000000000000000000000000000000001d0d8'}]
----request_func eth_blockNumber []
----request_func eth_getBlockByNumber [15, False]
----request_func eth_sendTransaction [{'from': '0x88224Fe4e4954C29d1D765eBe39331186fC259CF', 'to': '0x88224Fe4e4954C29d1D765eBe39331186fC259CF', 'data': '0x55241077000000000000000000000000000000000000000000000000000000000001d0d8', 'gas': 100088}]
[{'from': '0x88224Fe4e4954C29d1D765eBe39331186fC259CF', 'to': '0x88224Fe4e4954C29d1D765eBe39331186fC259CF', 'data': '0x55241077000000000000000000000000000000000000000000000000000000000001d0d8', 'gas': 100088}]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "../../programs/pyeos/tests/evm/evm/et.py", line 169, in <module>
    test()
  File "../../programs/pyeos/tests/evm/evm/et.py", line 144, in test
    call_contract(contract_interface)
  File "../../programs/pyeos/tests/evm/evm/et.py", line 129, in call_contract
    r = contract_instance.setValue(119000, transact={'from': contract_address})
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/contract.py", line 893, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/contract.py", line 906, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/contract.py", line 1156, in transact
    **self.kwargs
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/contract.py", line 1459, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/eth.py", line 268, in sendTransaction
    [transaction],
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/Users/tony/Work/pyeos/externals/python/dist/lib/python3.7/site-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "../../programs/pyeos/tests/evm/evm/et.py", line 38, in request_func_
    r, cost = eosapi.push_evm_action(params[0]['to'], params[0]['data'], {params[0]['from']:'active'}, True)
NameError: name 'eosapi' is not defined

**Comment by learnforpractice** [comment]
programs/pyeos/tests/evm/evm/et.py has been deprecated, 
please use programs/pyeos/tests/evm/evm/t.py as an example
